# Generated by Django 2.1.2 on 2018-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_auto_20181022_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
