# Generated by Django 2.1.2 on 2018-10-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_minina',
            new_name='idade_min',
        ),
    ]
